encoding: utf-8

# SEO相关信息
title: cqnswp Blog
description: cqnswp 的个人博客
keywords: cqnswp,Blog,Html,php
author: cqnswp
footerText: 'Copyright © 2020 渝ICP备19017069号'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://blog.cqnswp.ltd/'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
#tucaoUrl: 'https://blog.csdn.net/qq_38626043'

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 简历
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: true

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 个人CSDN博客
    url: https://blog.csdn.net/qq_38626043

  - title: GuiXie
    url: https://www.guixieblog.com/

  - title: zjun's blog
    url: https://www.zjun.info/
  - title: 恸
    url: http://blog.lpitiless.pro:12524/
